"""Generate C++ fixtures for the official ONNX NonMaxSuppression cases."""

from pathlib import Path
import struct
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

from nms_cases import NMS_CASES


def _require_ordered_corners(case):
    if int(case.get("center_point_box", 0)) != 0:
        raise SystemExit(
            f"{case['name']}: educational NMS is corners-only; "
            "omit center_point_box cases from nms_cases.py"
        )
    for batch in case["boxes"]:
        for box in batch:
            y1, x1, y2, x2 = box
            if y1 > y2 or x1 > x2:
                raise SystemExit(
                    f"{case['name']}: box {box} is not y1<=y2, x1<=x2; "
                    "omit flipped-coordinate cases from nms_cases.py"
                )

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT = REPO_ROOT / "test" / "unit_test" / "include" / "nms_onnx_cases.hpp"


def _flatten(values):
    for value in values:
        if isinstance(value, (list, tuple)):
            yield from _flatten(value)
        else:
            yield value


def _f32(value):
    rounded = struct.unpack("f", struct.pack("f", float(value)))[0]
    text = format(rounded, ".9g")
    if text in {"inf", "-inf", "nan"}:
        raise ValueError(f"non-finite float in fixture: {value}")
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text + "f"


def _c_name(name):
    return "".join(ch if ch.isalnum() else "_" for ch in name)


def _emit_float_array(name, values):
    body = ", ".join(_f32(value) for value in _flatten(values))
    return f"static const float {name}[] = {{ {body} }};"


def _emit_index_array(name, values):
    body = ", ".join(str(int(value)) for value in _flatten(values))
    return f"static const int64_t {name}[] = {{ {body} }};"


def main():
    chunks = [
        "// Generated by test/GoldenReference/generate_cpp_fixtures.py.",
        "// Do not edit by hand; regenerate after changing nms_cases.py.",
        "#pragma once",
        "",
        '#include "types.hpp"',
        "",
        "#include <cstdint>",
        "",
        "struct NMSOnnxCase",
        "{",
        "    const char* name;",
        "    int num_batches;",
        "    int num_classes;",
        "    int spatial_dim;",
        "    CenterPointBox center_point_box;",
        "    int64_t max_output_boxes_per_class;",
        "    float iou_threshold;",
        "    const float* score_threshold;",
        "    const float* boxes;",
        "    const float* scores;",
        "    const int64_t* expected_indices;",
        "    int expected_count;",
        "};",
        "",
    ]

    case_entries = []
    for case in NMS_CASES:
        _require_ordered_corners(case)
        c_name = _c_name(case["name"])
        boxes_name = f"kBoxes_{c_name}"
        scores_name = f"kScores_{c_name}"
        expected_name = f"kExpected_{c_name}"
        score_name = f"kScoreThreshold_{c_name}"

        chunks.append(_emit_float_array(boxes_name, case["boxes"]))
        chunks.append(_emit_float_array(scores_name, case["scores"]))
        chunks.append(_emit_index_array(expected_name, case["expected_indices"]))

        if case.get("score_threshold") is None:
            score_pointer = "nullptr"
        else:
            chunks.append(_emit_float_array(score_name, [case["score_threshold"]]))
            score_pointer = score_name

        center_point_box = (
            "CenterPointBox::Center"
            if int(case.get("center_point_box", 0)) == 1
            else "CenterPointBox::Corners"
        )
        expected_count = len(case["expected_indices"])
        case_entries.append(
            "    { "
            f"\"{case['name']}\", "
            f"{len(case['boxes'])}, "
            f"{len(case['scores'][0])}, "
            f"{len(case['boxes'][0])}, "
            f"{center_point_box}, "
            f"{int(case['max_output_boxes_per_class'])}, "
            f"{_f32(case['iou_threshold'])}, "
            f"{score_pointer}, "
            f"{boxes_name}, "
            f"{scores_name}, "
            f"{expected_name}, "
            f"{expected_count} "
            "},"
        )
        chunks.append("")

    chunks.append("static const NMSOnnxCase kNMSOnnxCases[] = {")
    chunks.extend(case_entries)
    chunks.append("};")
    chunks.append("")
    chunks.append(
        "static const int kNMSOnnxCaseCount = "
        "static_cast<int>(sizeof(kNMSOnnxCases) / sizeof(kNMSOnnxCases[0]));"
    )
    chunks.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(chunks), encoding="utf-8")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
