// Generated by test/GoldenReference/generate_cpp_fixtures.py.
// Do not edit by hand; regenerate after changing nms_cases.py.
#pragma once

#include "types.hpp"

#include <cstdint>

struct NMSOnnxCase
{
    const char* name;
    int num_batches;
    int num_classes;
    int spatial_dim;
    CenterPointBox center_point_box;
    int64_t max_output_boxes_per_class;
    float iou_threshold;
    const float* score_threshold;
    const float* boxes;
    const float* scores;
    const int64_t* expected_indices;
    int expected_count;
};

static const float kBoxes_suppress_by_IOU[] = { 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.100000001f, 1.0f, 1.10000002f, 0.0f, -0.100000001f, 1.0f, 0.899999976f, 0.0f, 10.0f, 1.0f, 11.0f, 0.0f, 10.1000004f, 1.0f, 11.1000004f, 0.0f, 100.0f, 1.0f, 101.0f };
static const float kScores_suppress_by_IOU[] = { 0.899999976f, 0.75f, 0.600000024f, 0.949999988f, 0.5f, 0.300000012f };
static const int64_t kExpected_suppress_by_IOU[] = { 0, 0, 3, 0, 0, 0, 0, 0, 5 };
static const float kScoreThreshold_suppress_by_IOU[] = { 0.0f };

static const float kBoxes_suppress_by_IOU_and_scores[] = { 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.100000001f, 1.0f, 1.10000002f, 0.0f, -0.100000001f, 1.0f, 0.899999976f, 0.0f, 10.0f, 1.0f, 11.0f, 0.0f, 10.1000004f, 1.0f, 11.1000004f, 0.0f, 100.0f, 1.0f, 101.0f };
static const float kScores_suppress_by_IOU_and_scores[] = { 0.899999976f, 0.75f, 0.600000024f, 0.949999988f, 0.5f, 0.300000012f };
static const int64_t kExpected_suppress_by_IOU_and_scores[] = { 0, 0, 3, 0, 0, 0 };
static const float kScoreThreshold_suppress_by_IOU_and_scores[] = { 0.400000006f };

static const float kBoxes_limit_output_size[] = { 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.100000001f, 1.0f, 1.10000002f, 0.0f, -0.100000001f, 1.0f, 0.899999976f, 0.0f, 10.0f, 1.0f, 11.0f, 0.0f, 10.1000004f, 1.0f, 11.1000004f, 0.0f, 100.0f, 1.0f, 101.0f };
static const float kScores_limit_output_size[] = { 0.899999976f, 0.75f, 0.600000024f, 0.949999988f, 0.5f, 0.300000012f };
static const int64_t kExpected_limit_output_size[] = { 0, 0, 3, 0, 0, 0 };
static const float kScoreThreshold_limit_output_size[] = { 0.0f };

static const float kBoxes_single_box[] = { 0.0f, 0.0f, 1.0f, 1.0f };
static const float kScores_single_box[] = { 0.899999976f };
static const int64_t kExpected_single_box[] = { 0, 0, 0 };
static const float kScoreThreshold_single_box[] = { 0.0f };

static const float kBoxes_identical_boxes[] = { 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f };
static const float kScores_identical_boxes[] = { 0.899999976f, 0.899999976f, 0.899999976f, 0.899999976f, 0.899999976f, 0.899999976f, 0.899999976f, 0.899999976f, 0.899999976f, 0.899999976f };
static const int64_t kExpected_identical_boxes[] = { 0, 0, 0 };
static const float kScoreThreshold_identical_boxes[] = { 0.0f };

static const float kBoxes_two_classes[] = { 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.100000001f, 1.0f, 1.10000002f, 0.0f, -0.100000001f, 1.0f, 0.899999976f, 0.0f, 10.0f, 1.0f, 11.0f, 0.0f, 10.1000004f, 1.0f, 11.1000004f, 0.0f, 100.0f, 1.0f, 101.0f };
static const float kScores_two_classes[] = { 0.899999976f, 0.75f, 0.600000024f, 0.949999988f, 0.5f, 0.300000012f, 0.899999976f, 0.75f, 0.600000024f, 0.949999988f, 0.5f, 0.300000012f };
static const int64_t kExpected_two_classes[] = { 0, 0, 3, 0, 0, 0, 0, 1, 3, 0, 1, 0 };
static const float kScoreThreshold_two_classes[] = { 0.0f };

static const float kBoxes_two_batches[] = { 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.100000001f, 1.0f, 1.10000002f, 0.0f, -0.100000001f, 1.0f, 0.899999976f, 0.0f, 10.0f, 1.0f, 11.0f, 0.0f, 10.1000004f, 1.0f, 11.1000004f, 0.0f, 100.0f, 1.0f, 101.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.100000001f, 1.0f, 1.10000002f, 0.0f, -0.100000001f, 1.0f, 0.899999976f, 0.0f, 10.0f, 1.0f, 11.0f, 0.0f, 10.1000004f, 1.0f, 11.1000004f, 0.0f, 100.0f, 1.0f, 101.0f };
static const float kScores_two_batches[] = { 0.899999976f, 0.75f, 0.600000024f, 0.949999988f, 0.5f, 0.300000012f, 0.899999976f, 0.75f, 0.600000024f, 0.949999988f, 0.5f, 0.300000012f };
static const int64_t kExpected_two_batches[] = { 0, 0, 3, 0, 0, 0, 1, 0, 3, 1, 0, 0 };
static const float kScoreThreshold_two_batches[] = { 0.0f };

static const float kBoxes_iou_threshold_boundary[] = { 0.0f, 0.0f, 1.0f, 1.0f, 0.5f, 0.5f, 1.5f, 1.5f };
static const float kScores_iou_threshold_boundary[] = { 0.899999976f, 0.800000012f };
static const int64_t kExpected_iou_threshold_boundary[] = { 0, 0, 0, 0, 0, 1 };
static const float kScoreThreshold_iou_threshold_boundary[] = { 0.0f };

static const NMSOnnxCase kNMSOnnxCases[] = {
    { "suppress_by_IOU", 1, 1, 6, CenterPointBox::Corners, 3, 0.5f, kScoreThreshold_suppress_by_IOU, kBoxes_suppress_by_IOU, kScores_suppress_by_IOU, kExpected_suppress_by_IOU, 3 },
    { "suppress_by_IOU_and_scores", 1, 1, 6, CenterPointBox::Corners, 3, 0.5f, kScoreThreshold_suppress_by_IOU_and_scores, kBoxes_suppress_by_IOU_and_scores, kScores_suppress_by_IOU_and_scores, kExpected_suppress_by_IOU_and_scores, 2 },
    { "limit_output_size", 1, 1, 6, CenterPointBox::Corners, 2, 0.5f, kScoreThreshold_limit_output_size, kBoxes_limit_output_size, kScores_limit_output_size, kExpected_limit_output_size, 2 },
    { "single_box", 1, 1, 1, CenterPointBox::Corners, 3, 0.5f, kScoreThreshold_single_box, kBoxes_single_box, kScores_single_box, kExpected_single_box, 1 },
    { "identical_boxes", 1, 1, 10, CenterPointBox::Corners, 3, 0.5f, kScoreThreshold_identical_boxes, kBoxes_identical_boxes, kScores_identical_boxes, kExpected_identical_boxes, 1 },
    { "two_classes", 1, 2, 6, CenterPointBox::Corners, 2, 0.5f, kScoreThreshold_two_classes, kBoxes_two_classes, kScores_two_classes, kExpected_two_classes, 4 },
    { "two_batches", 2, 1, 6, CenterPointBox::Corners, 2, 0.5f, kScoreThreshold_two_batches, kBoxes_two_batches, kScores_two_batches, kExpected_two_batches, 4 },
    { "iou_threshold_boundary", 1, 1, 2, CenterPointBox::Corners, 3, 0.142857149f, kScoreThreshold_iou_threshold_boundary, kBoxes_iou_threshold_boundary, kScores_iou_threshold_boundary, kExpected_iou_threshold_boundary, 2 },
};

static const int kNMSOnnxCaseCount = static_cast<int>(sizeof(kNMSOnnxCases) / sizeof(kNMSOnnxCases[0]));
